llama2-7b:
  hf_key: "NousResearch/Llama-2-7b-chat-hf"
  question_start_tag: "[INST] "
  question_end_tag: " [/INST]"
  answer_tag: ""
  flash_attention2: "true"
  gradient_checkpointing: "true"
  ft_model_path: "paper_models/final_ft_noLORA_5_epochs_inst_lr1e-05_llama2-7b_full/checkpoint-625" #this model will be used for unlearning by defauly
llama3-8b:
  hf_key: "/net/scratch/hscra/plgrid/plgvltkv/unbranding/models/llama-3.1-8b"
  ft_model_path: "/net/scratch/hscra/plgrid/plgvltkv/unbranding/models/llama-3.1-8b"
  flash_attention2: "false"
  gradient_checkpointing: "true"
  question_start_tag: "<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n\n"
  question_end_tag: "<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"
  answer_tag: "<|eot_id|>"
mistral-small:
  hf_key: "/net/scratch/hscra/plgrid/plgvltkv/unbranding/models/mistral-small"
  ft_model_path: "/net/scratch/hscra/plgrid/plgvltkv/unbranding/models/mistral-small"
  flash_attention2: "false"
  gradient_checkpointing: "true"
  question_start_tag: "[INST] "
  question_end_tag: " [/INST]"
  answer_tag: "</s>"                   
qwen-14b:
  hf_key: "/net/scratch/hscra/plgrid/plgvltkv/unbranding/models/qwen-14b"
  ft_model_path: "/net/scratch/hscra/plgrid/plgvltkv/unbranding/models/qwen-14b"
  flash_attention2: "false"
  gradient_checkpointing: "true"
  question_start_tag: "<|im_start|>user\n"
  question_end_tag: "<|im_end|>\n<|im_start|>assistant\n"
  answer_tag: "<|im_end|>"              
qwen-32b:
  hf_key: "/net/scratch/hscra/plgrid/plgvltkv/unbranding/models/qwen-32b"
  ft_model_path: "/net/scratch/hscra/plgrid/plgvltkv/unbranding/models/qwen-32b"
  flash_attention2: "false"
  gradient_checkpointing: "true"
  question_start_tag: "<|im_start|>user\n"
  question_end_tag: "<|im_end|>\n<|im_start|>assistant\n"
  answer_tag: "<|im_end|>"
gemma-4-31b-it:
  hf_key: "/net/scratch/hscra/plgrid/plgvltkv/unbranding/models/gemma-4-31b-it"
  ft_model_path: "/net/scratch/hscra/plgrid/plgvltkv/unbranding/models/gemma-4-31b-it"
  flash_attention2: "false"
  gradient_checkpointing: "true"
  question_start_tag: "<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n\n"
  question_end_tag: "<|eot_id|><|start_header_id|>model<|end_header_id|>\n\n"
  answer_tag: "<|eot_id|>"
phi:
  hf_key: "microsoft/phi-1_5"
  question_start_tag: "Question: "
  question_end_tag: "\n"
  answer_tag: "Answer: "
  flash_attention2: "false"
  gradient_checkpointing: "false"
  ft_model_path: "paper_models/final_ft_noLORA_5_epochs_inst_lr2e-05_phi_full/checkpoint-625"
stablelm:
  hf_key: "stabilityai/stablelm-3b-4e1t"
  question_start_tag: "Question: "
  question_end_tag: "\n"
  answer_tag: "Answer: "
  flash_attention2: "false"
  gradient_checkpointing: "false"
  ft_model_path: "paper_models/final_ft_noLORA_5_epochs_inst_lr1e-05_stablelm/checkpoint-625"
pythia-1.4:
  hf_key: "EleutherAI/pythia-1.4b-deduped"
  question_start_tag: "Question: "
  question_end_tag: "\n"
  answer_tag: "Answer: "
  flash_attention2: "false"
  gradient_checkpointing: "false"
zephyr-7b-beta:
  hf_key: "HuggingFaceH4/zephyr-7b-beta"
  flash_attention2: "true"
  gradient_checkpointing: "true"
  
