brand: Audi

models:
  base:
    path: ../../../../unbranding/models/Qwen3-8B

  judge:
    path: ../../../../unbranding/models/Qwen3-32B

experiment:

  model_family: Qwen3-8b

  experiments_root: ../../../../unbranding/models_unlearned/NPO/AUDI/qwen3-8b

  target_epochs:
    - 1
    - 5
    - 7
    - 10
    - 15
    - 20
    - 25

datasets:
  domain_retain: ../datasets/AUTO/AUDI/EVAL/test_retain_automotive.jsonl
  alpaca: ../datasets/AUTO/AUDI/EVAL/test_retain.jsonl
  world_facts: ../datasets/AUTO/AUDI/EVAL/test_world_facts.jsonl
  thesis: ../datasets/AUTO/AUDI/EVAL/thesis.jsonl
  short_thesis: ../datasets/AUTO/AUDI/EVAL/short_thesis.jsonl
  choices: ../datasets/AUTO/AUDI/EVAL/choices.jsonl

results:
  answers_dir: results/answers
  metrics_dir: results/metrics
  aggregated_dir: results/aggregated

generation:
  max_new_tokens: 64

evaluation:
  batch_size: 64
  seed: 42

metrics:
  - rouge
  - probability
  - brand_mention_judge
  - brand_mention_spacy
  - trade_dress
  - world_facts
  - judge_quality